package com.waterminn.smeem_expandable_calendar.datasource

import com.waterminn.smeem_expandable_calendar.model.Date
import java.time.LocalDate
import java.time.format.DateTimeFormatter

val weeklyDateList = arrayOf(
    listOf(
        LocalDate.parse("2023-10-01", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-02", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-03", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-04", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-05", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-06", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-07", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
    ),
    listOf(
        LocalDate.parse("2023-10-08", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-09", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-10", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-11", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-12", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-13", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-14", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
    ),
    listOf(
        LocalDate.parse("2023-10-15", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-16", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-17", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-18", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-19", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-20", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-21", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
    ),
    listOf(
        LocalDate.parse("2023-10-22", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-23", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-24", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-25", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-26", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-27", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-28", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
    )
)

val weeklyDateArray: Array<List<Date>> = weeklyDateList.map { week ->
    week.map { date ->
        Date(
            day = date,
            isCurrentMonth = true,
            isDiaryWritten = false
        )
    }
}.toTypedArray()

val monthlyDateList = arrayOf(
    listOf(
        LocalDate.parse("2023-08-27", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-08-28", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-08-29", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-08-30", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-08-31", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-01", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-02", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-03", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-04", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-05", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-06", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-07", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-08", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-09", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-10", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-11", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-12", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-13", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-14", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-15", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-16", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-17", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-18", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-19", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-20", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-21", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-22", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-23", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-24", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-25", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-26", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-27", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-28", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-29", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-09-30", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
    ),
    listOf(
        LocalDate.parse("2023-10-01", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-02", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-03", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-04", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-05", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-06", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-07", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-08", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-09", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-10", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-11", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-12", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-13", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-14", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-15", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-16", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-17", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-18", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-19", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-20", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-21", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-22", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-23", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-24", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-25", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-26", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-27", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-28", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-29", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-30", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-31", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-01", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-02", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-03", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-04", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
    ),
    listOf(
        LocalDate.parse("2023-10-29", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-30", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-10-31", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-01", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-02", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-03", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-04", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-05", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-06", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-07", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-08", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-09", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-10", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-11", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-12", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-13", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-14", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-15", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-16", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-17", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-18", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-19", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-20", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-21", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-22", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-23", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-24", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-25", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-26", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-27", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-28", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-29", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-11-30", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-12-01", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
        LocalDate.parse("2023-12-02", DateTimeFormatter.ofPattern("yyyy-MM-dd")),
    ),
)